#!/usr/bin/env Rscript

library(knitr)
stopifnot('_source' %in% list.files()) # run me from the root directory
render_jekyll()

opts_chunk$set(r.width = quote(options(width = 65)),
               pars = list(mar = c(4, 4, .1, .1), mgp = c(2, 1, 0), bg = 'white'))
knit_hooks$set(pars = function(before, options, envir) {
  if (before) do.call(par, options$pars)
}, rgl = hook_rgl, crop = hook_pdfcrop)

options(reindent.spaces = 2) # formatR

local({
  f = commandArgs(TRUE)
  base = sub('\\.[Rr]md$', '', basename(f))
  setwd('_figures/')
  # each source file corresponds to a separate fig.path and cache.path
  opts_chunk$set(fig.path = paste(base, '', sep = '/'), cache = TRUE,
                 cache.path = paste('../_cache', base, '', sep = '/'))
  # add root.url to images
  opts_knit$set(base.url = 'http://animation.r-forge.r-project.org/vistat/',
                animation.fun = hook_scianimator)
  # if not called from `rake knit`
  if (!grepl('^\\./_source/', f)) {
    setwd('../figures/')
    opts_chunk$set(cache.path = paste('../cache', base, '', sep = '/'))
    opts_knit$set(base.url = '/figures/')
  }
  knit(file.path('..', f), paste('../_posts/', base, '.md', sep = ''), envir = globalenv())
})
