#!/usr/bin/env Rscript

# install dependencies
for (i in setdiff(c(
  'Cairo',
  'animation',
  'knitr',
  'hexbin'
), .packages(TRUE))) {
  install.packages(i)
}

# formatR indent 2 spaces; print width 65; no progress
options(reindent.spaces = 2, KNITR_WIDTH = 65)

library(knitr)
stopifnot('_source' %in% list.files()) # run me from the root directory
render_jekyll()

opts_chunk$set(
  pars = list(mar = c(4, 4, .1, .1), mgp = c(2, 1, 0), bg = 'white'),
  cache = TRUE
)
knit_hooks$set(pars = function(before, options, envir) {
  if (before) do.call(par, options$pars)
}, rgl = hook_rgl, crop = hook_pdfcrop)
opts_knit$set(animation.fun = hook_scianimator, stop_on_error = 2L)

invisible(local({
  f = commandArgs(TRUE)
  base = sub('\\.[Rr]md$', '', basename(f))
  # each source file corresponds to a separate fig.path and cache.path
  opts_chunk$set(cache.path = paste('cache', base, '', sep = '/'),
                 fig.path = paste(base, '', sep = '/'))
  # generate figures to the ./figure/ directory
  if (!file.exists('figure/')) dir.create('figure')
  opts_knit$set(base.dir = normalizePath('figure', mustWork = TRUE))
  # save images to R-Forge; I can simply save them to my Dropbox folder, e.g.
  # http://dl.dropbox.com/u/15335397/vistat/ but the problem is that animations
  # do not work well under Google Chrome for some reason (SciAnimator keeps on
  # fetching images from Dropbox)
  opts_knit$set(base.url = if (as.character(file.info('figure/')[, 'mode']) != '2755') '/figure/' else {
    'http://isu.r-forge.r-project.org/vistat/'
  })
  message(f)
  knit(f, paste('_posts/', base, '.md', sep = ''), envir = globalenv(), quiet = TRUE)
}))
